---
permalink: san-host/task_preparing_for_cutover_when_transitioning_linux_host_dmmp_device_without_file_system.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, cutover, linux, dmmp, device, host 
summary: Se si sta eseguendo la transizione di un dispositivo DMMP senza un file system da un host Linux, è necessario eseguire diversi passaggi prima di entrare nella fase di cutover. 
---
= Preparazione per il cutover durante la transizione di un dispositivo DMMP host Linux senza un file system
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si sta eseguendo la transizione di un dispositivo DMMP senza un file system da un host Linux, è necessario eseguire diversi passaggi prima di entrare nella fase di cutover.

Per le configurazioni FC, è necessario disporre di connettività fabric e zoning per i controller Data ONTAP in cluster.

Per le configurazioni iSCSI, è necessario rilevare le sessioni iSCSI e accedere ai controller Data ONTAP in cluster.

* Per le transizioni basate sulla copia, eseguire questi passaggi prima di avviare l'operazione Storage Cutover nel 7-Mode Transition Tool (7MTT).
* Per le transizioni senza copia, eseguire questi passaggi prima di avviare l'operazione Export & Halt 7-Mode in 7MTT.


.Fasi
. Arrestare l'i/o nei punti di montaggio.
. Chiudere le applicazioni che accedono alle LUN in base alle raccomandazioni del vendor dell'applicazione.
. Scaricare il dispositivo DMMP o l'alias LUN 7-Mode:
+
`*multipath -f _device_name_*`

+
Se necessario, è possibile ottenere il nome del dispositivo DMMP dalla colonna *OS Device ID* (ID dispositivo sistema operativo) nella scheda SAN host LUN (LUN host SAN) del _Inventory Assessment Workbook_.


