---
permalink: san-host/task_preparing_for_cutover_when_transitioning_luns_with_mounts_using_dmmp_aliases_on_linux_hosts.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, cutover, phase, lun, point, dmmp, device, names 
summary: Se si sta eseguendo la transizione di un LUN con un punto di montaggio utilizzando un nome alias su un host Linux, è necessario eseguire diversi passaggi prima di entrare nella fase di cutover. 
---
= Preparazione per la fase di cutover durante la transizione dei LUN con punti di montaggio utilizzando i nomi dei dispositivi DMMP sugli host Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si sta eseguendo la transizione di un LUN con un punto di montaggio utilizzando un nome alias su un host Linux, è necessario eseguire diversi passaggi prima di entrare nella fase di cutover.

Per le configurazioni FC, è necessario disporre di connettività fabric e zoning per i controller Data ONTAP in cluster.

Per le configurazioni iSCSI, è necessario rilevare le sessioni iSCSI e accedere ai controller Data ONTAP in cluster.

* Per le transizioni basate sulla copia, eseguire questi passaggi prima di avviare l'operazione Storage Cutover nel 7-Mode Transition Tool (7MTT).
* Per le transizioni senza copia, eseguire questi passaggi prima di avviare l'operazione Export & Halt 7-Mode Systems nel 7MTT.


.Fasi
. Arrestare l'i/o nei punti di montaggio.
. Chiudere le applicazioni che accedono alle LUN in base alle raccomandazioni del vendor dell'applicazione.
. Smontare i dispositivi DMMP:
+
`*umount _dir_name_*`

. Svuotare il LUN 7-Mode DMMP Device ID (ID dispositivo DMMP LUN 7-Mode):
+
`*multipath -f _device_name_*`

+
Se necessario, è possibile ottenere il nome del dispositivo DDMP dalla colonna *OS Device ID* nella scheda *SAN host LUN* del _Inventory Assessment Workbook_.



*Informazioni correlate*

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[Raccolta di informazioni pre-transizione dal Workbook per la valutazione dell'inventario]
