---
permalink: san-host/task_preparing_linux_guest_operating_systems_for_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, linux, operating, system 
summary: 'Se le LUN 7-Mode sono mappate come RDM (PTRDM) fisico compatibile con le macchine virtuali Linux per il dispositivo di boot, è necessario eseguire alcuni passaggi per preparare le macchine virtuali Linux per la transizione.' 
---
= Preparazione dei sistemi operativi guest Linux per la transizione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se le LUN 7-Mode sono mappate come RDM (PTRDM) fisico compatibile con le macchine virtuali Linux (VM) per il dispositivo di boot, è necessario eseguire alcuni passaggi per preparare le macchine virtuali Linux per la transizione.

* Per le transizioni basate sulla copia, eseguire questi passaggi prima di avviare l'operazione Storage Cutover nel 7-Mode Transition Tool (7MTT).
* Per le transizioni senza copia, eseguire questi passaggi prima di avviare l'operazione Export & Halt 7-Mode Systems nel 7MTT.


.Fasi
. Ottenere i numeri di serie dei dispositivi SCSI:
+
`*cat /boot/grub/menu.lst*`

+
Nell'esempio seguente, i numeri dei dispositivi SCSI sono 360a9800032466879362b45777447462d-part2 e 360a9800032466879362b45777447462d-part1:

+
[listing]
----
# cat /boot/grub/menu.lst
...
kernel /boot/vmlinuz-3.0.13-0.27-default root=/dev/disk/by-id/scsi-
360a9800032466879362b45777447462d-part2 resume=/dev/disk/by-id/scsi-
360a9800032466879362b45777447462d-part1
----
. Determinare la mappatura tra i numeri di serie dei dispositivi SCSI e i dispositivi/partizioni SCSI:
+
`*# ls -l /dev/disk/by-id*`

+
L'esempio seguente mostra come viene visualizzata la mappatura delle relazioni. Il `SCSI devices/partitions` vengono visualizzati dopo `SCSI device/partition serial numbers`. In questo esempio, `../../sda, ../../sda1, and ../../sda2` Sono periferiche/partizioni SCSI.

+
[listing]
----
lrwxrwxrwx 1 root root 9 Oct 27 06:54 scsi-360a9800032466879362b45777447462d -> ../../sda
   lrwxrwxrwx 1 root root 10 Oct 27 05:09 scsi-360a9800032466879362b45777447462d-part1 -> ../../sda1
   lrwxrwxrwx 1 root root 10 Oct 27 02:21 scsi-360a9800032466879362b45777447462d-part2 -> ../../sda2
----
. Determinare la mappatura tra i percorsi dei dispositivi SCSI e gli UUID:
+
`*ls -l /dev/disk/by-uuid*`

+
L'esempio seguente mostra come viene visualizzata la mappatura delle relazioni. In questo esempio, `33d43a8b-cfae-4ac4-9355-36b479cfa524` È l'UUID per il dispositivo SCSI/partizione sda2`, `603e01f8-7873-440a-9182-878abff17143` È l'UUID per il dispositivo SCSI/partizione sdb, e. `c50b757b-0817-4c19-8291-0d14938f7f0f` È l'UUID per il dispositivo SCSI/partizione sda1.

+
[listing]
----
 lrwxrwxrwx 1 root root 10 Oct 27 02:21 33d43a8b-cfae-4ac4-9355-36b479cfa524 -> ../../sda2
   lrwxrwxrwx 1 root root 9 Oct 27 06:54 603e01f8-7873-440a-9182-878abff17143 -> ../../sdb
   lrwxrwxrwx 1 root root 10 Oct 27 05:09 c50b757b-0817-4c19-8291-0d14938f7f0f -> ../../sda1
----
. Utilizzare l'UUID per aggiornare il riferimento del dispositivo nell'avvio di GRUB `menu.lst` Associandolo al percorso del dispositivo SCSI e al numero di serie SCSI.
+
[listing]
----
#blkid
/dev/sda1: UUID="c50b757b-0817-4c19-8291-0d14938f7f0f" TYPE="swap"
/dev/sda2: UUID="33d43a8b-cfae-4ac4-9355-36b479cfa524" TYPE="ext3"
/dev/sdb: UUID="603e01f8-7873-440a-9182-878abff17143" SEC_TYPE="ext2" TYPE="ext3"
----
. Utilizzare l'UUID appena recuperato per aggiornare il riferimento del dispositivo nell'avvio di GRUB `menu.lst` file.
+
Nell'esempio riportato di seguito viene illustrato il `menu.lst` file dopo l'aggiornamento:

+
[listing]
----
# Modified by YaST2. Last modification on Fri Oct 17 02:08:40 EDT 2014
default 0
timeout 8
##YaST - generic_mbr
gfxmenu (hd0,1)/boot/message
##YaST - activate
###Don't change this comment - YaST2 identifier: Original name: linux###
title SUSE Linux Enterprise Server 11 SP2 - 3.0.13-0.27
root (hd0,1)
kernel /boot/vmlinuz-3.0.13-0.27-default root=/dev/disk/by-uuid/e5127cdf-8b30-
418e-b0b2-35727161ef41 resume=/dev/disk/by-uuid/d9133964-d2d1-4e29-b064-7316c5ca5566
splash=silent crashkernel=128M-:64M showopts vga=0x314
initrd /boot/initrd-3.0.13-0.27-default
----
. Aggiornare `/etc/fstab` file:
+
.. Utilizzare l'UUID appena recuperato per aggiornare il riferimento del dispositivo in `/etc/fstab` file.
+
L'esempio seguente mostra un `/etc/fstab` File con numero di serie SCSI:

+
[listing]
----
/dev/disk/by-id/scsi-360a9800032466879362b45777447462d-part1 swap swap
defaults 0 0
/dev/disk/by-id/scsi-360a9800032466879362b45777447462d-part2 / ext3
acl,user_xattr 1 1
proc /proc proc defaults 0 0
sysfs /sys sysfs noauto 0 0
debugfs /sys/kernel/debug debugfs noauto 0 0
devpts /dev/pts devpts mode=0620,gid=5 0 0
----
.. Sostituire il riferimento al numero di serie SCSI con l'UUID.
+
L'esempio seguente mostra un `/etc/fstab` File aggiornato per sostituire il numero di serie SCSI con UUID:

+
[listing]
----
cat /etc/fstab
UUID="c50b757b-0817-4c19-8291-0d14938f7f0f swap swap defaults
0 0
UUID="33d43a8b-cfae-4ac4-9355-36b479cfa524 / ext3 acl,user_xattr
1 1
proc /proc proc defaults 0 0
sysfs /sys sysfs noauto 0 0
debugfs /sys/kernel/debug debugfs noauto 0 0
devpts /dev/pts devpts mode=0620,gid=5 0 0
----



