---
permalink: san-host/task_testing_dmmp_devices_with_file_systems_on_rhel_hosts_before_cutover_phase.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, dmmp, devices, rhel, hosts, cutover, phase 
summary: 'Se stai utilizzando 7-Mode Transition Tool 2.2 o versione successiva e Data ONTAP 8.3.2 o versione successiva per eseguire una transizione basata su copia dell"host Red Hat Enterprise Linux (RHEL), È possibile testare i LUN Data ONTAP in cluster in transizione per verificare che sia possibile montare il dispositivo DMMP prima della fase di cutover. L"host di origine può continuare a eseguire i/o sui LUN 7-Mode di origine durante il test.' 
---
= Test dei dispositivi DMMP con file system su host RHEL prima della fase di cutover delle transizioni basate sulla copia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si utilizza 7-Mode Transition Tool (7MTT) 2.2 o versione successiva e Data ONTAP 8.3.2 o versione successiva per eseguire una transizione basata su copia dell'host Red Hat Enterprise Linux (RHEL), È possibile testare i LUN Data ONTAP in cluster in transizione per verificare che sia possibile montare il dispositivo DMMP prima della fase di cutover. L'host di origine può continuare a eseguire i/o sui LUN 7-Mode di origine durante il test.

Le nuove LUN Data ONTAP in cluster devono essere mappate all'host di test e le LUN devono essere pronte per la transizione.

È necessario mantenere la parità hardware tra l'host di test e l'host di origine.

Eseguire questa procedura sull'host di test.

. Una volta completata la copia dei dati di riferimento, selezionare *Test Mode* nell'interfaccia utente 7MTT.
. Nell'interfaccia utente 7MTT, fare clic su *Apply Configuration* (Applica configurazione).
. Ottenere i nuovi nomi dei dispositivi SCSI per i LUN Data ONTAP in cluster:
+
`*sanlun lun show*`

+
Nell'esempio seguente, `/dev/sdl` È il nome del dispositivo SCSI per `lun_dmmp_raw` LUN, e. `/dev/sdk` È il nome del dispositivo SCSI per `lun_dmmp_raw_alias` LUN:

+
[listing]
----
[root@ibmx3550-229-108 /]# sanlun lun show
controller(7mode/E-Series)/
vserver (cDOT/FlashRay) lun-pathname               filename
-----------------------------------------------------------
vs_brb  /vol/dmmp_raw_vol/lun_dmmp_raw              /dev/sdl
vs_brb  /vol/dmmp_raw_alias_vol/lun_dmmp_raw_alias  /dev/sdk
----
. Configurare i dispositivi DMMP per i LUN Data ONTAP in cluster:
+
`*multipath*`

. Ottenere l'ID handle del dispositivo per le LUN Data ONTAP in cluster:
+
`*multipath -ll*`

+
Di seguito viene riportato un esempio di ID handle del dispositivo: "`3600a09804d532d79565d47617679764d`"

. Identificare il file system configurato sul dispositivo DMMP:
+
`*blkid | grep -i _device_handle_ID_*`

. Determinare se esiste una voce del punto di montaggio per il volume logico in `/etc/fstab` file sull'host di origine.
. Se esiste una voce del punto di montaggio per il volume logico sull'host di origine, modificare manualmente `/etc/fstab` sul test host per aggiungere le voci del punto di montaggio.
. Montare il LUN:
+
`*mount -a*`

. Verificare che il dispositivo DMMP sia montato:
+
`*mount*`

. Eseguire i test in base alle necessità.
. Una volta completato il test, spegnere l'host di test:
+
`*shutdown -h -t0 now*`

. Nell'interfaccia utente 7MTT, fare clic su *Finish Testing* (fine test).


Se le LUN Data ONTAP in cluster devono essere rimappate all'host di origine, è necessario preparare l'host di origine per la fase di cutover. Se i LUN Data ONTAP in cluster devono rimanere mappati all'host di test, non sono necessarie ulteriori operazioni sull'host di test.

*Informazioni correlate*

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[Raccolta di informazioni pre-transizione dal Workbook per la valutazione dell'inventario]

xref:task_preparing_for_cutover_when_transitioning_luns_with_mounts_using_dmmp_aliases_on_linux_hosts.adoc[Preparazione per la fase di cutover durante la transizione dei LUN con punti di montaggio utilizzando i nomi dei dispositivi DMMP sugli host Linux]
