---
permalink: san-host/task_replacing_7_mode_wwids_on_linux_host_after_transition_of_luns.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, 7, mode, wwids, linux, lun 
summary: 'Dopo la transizione del LUN, il WWID del LUN 7-Mode cambia. È necessario sostituirlo con l"ID WWID LUN ONTAP corrispondente prima di poter iniziare la manutenzione dei dati.' 
---
= Sostituzione dei WWID LUN 7-Mode sugli host Linux dopo la transizione dei LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo la transizione del LUN, il WWID del LUN 7-Mode cambia. È necessario sostituirlo con l'ID WWID LUN ONTAP corrispondente prima di poter iniziare la manutenzione dei dati.

Se si sta eseguendo una transizione senza copia (CFT), le procedure per il rehost vol devono essere completate.

Vedere link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-free/index.html["7-Mode Transition Tool Copy-Free Transition Guide"]per ulteriori informazioni.

* Per le transizioni basate sulla copia (CBT), eseguire questi passaggi dopo aver completato l'operazione di cutover dello storage in 7MTT.
* Per i CFT, eseguire questi passaggi dopo il completamento dell'operazione di importazione dati e configurazione nel 7MTT.


.Fasi
. Generare il file di mappatura LUN 7-Mode su ONTAP:
+
** Per i CBT, eseguire il seguente comando dall'host Linux in cui è installato 7MTT: +
`*transition cbt export lunmap -p project-name -o _file_path_*`
+
Ad esempio:

+
`*transition cbt export lunmap -p SanWorkLoad -o c:/Libraires/Documents/7-to-C-LUN-MAPPING.csv*`

** Per i CFT, eseguire il seguente comando dal sistema in cui è installato 7MTT: +
`*transition cft export lunmap -p _project-name_ -s _svm-name_ -o _output-file_*`
+
Ad esempio:

+
`*transition cft export lunmap -p SanWorkLoad -s svml -0 c:/Libraries/Documents/7-to-C-LUN-MAPPING-svml.csv*`

+

NOTE: È necessario eseguire questo comando per ciascuna delle macchine virtuali di storage (SVM).



. Prendere nota del nuovo ID handle del dispositivo LUN ONTAP dal file di mappatura LUN.
. Rimuovere i dispositivi SCSI creati per i LUN 7-Mode:
+
** Per rimuovere tutti i dispositivi SCSI: +
`*rescan-scsi-bus.sh -r*`
** Per rimuovere ciascun dispositivo SCSI singolarmente: +
`*echo 1> /sys/block/__SCSI_ID__/delete*`
+
Questo comando deve essere eseguito su tutti i dispositivi LUN SCSI 7-Mode. Consultare la colonna SCSI Device ID (ID dispositivo SCSI) nella scheda SAN host LUN (LUN host SAN) del _Inventory Assessment Workbook_ per identificare gli ID dei dispositivi SCSI per i LUN.



. Scopri le nuove LUN ONTAP:
+
`*rescan-scsi-bus.sh*`

. Identificare i dispositivi SCSI dei nuovi LUN ONTAP:
+
`*sanlun lun show*`

. Ottieni i WWID per i nuovi LUN ONTAP:
+
`*/lib/udev/scsi_id -g -u -d /dev _SCSI_dev_*`

. Se viene definito un alias DMMP, aggiornare il file /etc/multipath.conf in modo da sostituire l'ID WWID del LUN 7-Mode con l'ID WWID del LUN ONTAP corrispondente, in modo che l'alias DMMP punti al LUN Data ONTAP in cluster:
+
`*cat /etc/multipath.conf*`

. Configurare i dispositivi DMMP:
+
`*multipath*`

. Verificare che l'alias DMMP faccia riferimento correttamente all'ID WWID del LUN ONTAP:
+
`*multipath -11*`

+
Nell'output di esempio seguente, l'alias DMMP `dmmp_raw_lun` sta facendo riferimento `3600a098051764b2d4f3f453135452d31` Come WWID ONTAP:

+
[listing]
----
root@IBMx3550M3-229-169 ~]# multipath -ll dmmp_raw_lun
dmmp_raw_lun (3600a098051764b2d4f3f453135452d31) dm-8 NETAPP, LUN C-Mode
[size=1.0G] [features=3 queue_if_no_path pg_init_retries 50] [hwhandler=1 alua] [rw]
\_round-robin 0 [prio=50][enabled]
 \_5:0:0:6 sdx 	65:112 [active][ready]
	\_8:0:0:6 sdab 65:176 [active][ready]
\_round-robin 0 [prio=10][enabled]
 \_6:0:0:6 sdy 	65:128 [active][ready]
	\_7:0:0:6 sdaa 65:160 [active][ready]
----

