---
permalink: san-host/task_preparing_to_transition_solaris_host_data_luns_with_zfs_file_system.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, solaris, host, data, lun, zfs 
summary: Prima di eseguire la transizione dei LUN host Solaris con file system ZFS da Data ONTAP in 7-Mode a Clustered Data ONTAP, è necessario raccogliere le informazioni necessarie per il processo di transizione. 
---
= Preparazione alla transizione dei LUN dei dati host Solaris con il file system ZFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire la transizione dei LUN host Solaris con file system ZFS da Data ONTAP in 7-Mode a Clustered Data ONTAP, è necessario raccogliere le informazioni necessarie per il processo di transizione.

Questo vale per le transizioni basate sulla copia e le transizioni senza copia.

.Fasi
. Sul controller 7-Mode, identificare il nome del LUN da trasferire:
+
`*lun show*`

+
[listing]
----
 fas8040-shu01> lun show
        /vol/ufs/ufs1                  5g (5368709120)    (r/w, online, mapped)
        /vol/ufs/ufs2                  5g (5368709120)    (r/w, online, mapped)
        /vol/zfs/zfs1                  6g (6442450944)    (r/w, online, mapped)
        /vol/zfs/zfs2                  6g (6442450944)    (r/w, online, mapped)
----
. Sull'host, individuare il nome del file del dispositivo SCSI per il LUN:
+
`*sanlun lun show*`

+
Il nome del file del dispositivo SCSI si trova in `device filename` colonna.

+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
fas8040-shu01        /vol/zfs/zfs2    /dev/rdsk/c0t60A98000383035356C2447384D396550d0s2 scsi_vhci0 FCP        6g      7
fas8040-shu01        /vol/zfs/zfs1    /dev/rdsk/c0t60A98000383035356C2447384D39654Ed0s2 scsi_vhci0 FCP        6g      7
fas8040-shu01        /vol/ufs/ufs2    /dev/rdsk/c0t60A98000383035356C2447384D39654Ad0s2 scsi_vhci0 FCP        5g      7
fas8040-shu01        /vol/ufs/ufs1    /dev/rdsk/c0t60A98000383035356C2447384D396548d0s2 scsi_vhci0 FCP        5g      7
----
. Elencare lo zpool:
+
`*zpool list*`

. Registrare lo zpool e ottenere i dischi associati allo zpool:
+
`*zpool status _pool-name_*`

+
[listing]
----
# zpool list
NAME     SIZE  ALLOC   FREE  CAP  HEALTH  ALTROOT
n_pool  11.9G  2.67G  9.27G  22%  ONLINE  -

# zpool status
  pool: n_pool
 state: ONLINE
 scan: none requested
config:

        NAME                                     STATE     READ WRITE CKSUM
        n_pool                                   ONLINE       0     0     0
          c0t60A98000383035356C2447384D396550d0  ONLINE       0     0     0
          c0t60A98000383035356C2447384D39654Ed0  ONLINE       0     0     0

errors: No known data errors
----
. Elencare e registrare i set di dati ZFS all'interno di un pool di storage ZFS:
+
`*zfs list*`

+
[listing]
----
# zfs list
NAME           USED  AVAIL  REFER  MOUNTPOINT
n_pool        2.67G  9.08G   160K  /n_pool
n_pool/pool1  1.50G  2.50G  1.50G  /n_pool/pool1
n_pool/pool2  1.16G  2.84G  1.16G  /n_pool/pool2
----

