---
permalink: san-host/task_enabling_caw_on_a_datastore_using_esxi_cli.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, enable, caw, datastore, esxi, cli 
summary: 'Se non si dispone del supporto per il confronto e la scrittura (CAW) in Data ONTAP in modalità 7, è necessario attivare manualmente il supporto CAW quando si passa a Clustered Data ONTAP. Clustered Data ONTAP supporta CAW per impostazione predefinita.' 
---
= Abilitazione di CAW su un datastore utilizzando la CLI ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se non si dispone del supporto per il confronto e la scrittura (CAW) in Data ONTAP in modalità 7, è necessario attivare manualmente il supporto CAW quando si passa a Clustered Data ONTAP. Clustered Data ONTAP supporta CAW per impostazione predefinita.

* Non devono essere presenti i/o o VM in esecuzione attiva nel datastore VMFS.
* Il datastore deve essere rimontato, se è stato migrato.
* È necessario disporre del nuovo ID LUN ONTAP del file di mappatura 7-Mode Transition Tool (7MTT).


CAW deve essere attivato solo quando non sono in esecuzione alcun i/o o VM nel datastore VMFS.

* CAW deve essere attivato solo quando non sono in esecuzione alcun i/o o VM nel datastore VMFS.
* Per le transizioni basate sulla copia, eseguire questi passaggi dopo aver completato l'operazione di cutover dello storage in 7MTT.
* Per le transizioni senza copia, eseguire questi passaggi dopo il completamento dell'operazione Import Data & Configuration (Importa dati e configurazione) in 7MTT.


.Fasi
. Aprire il _Inventory Assessment Workbook_ generato da Inventory Collect Tool (ICT).
. Accedere alla scheda SAN host Filesystems (Filesystems host SAN).
. Verificare lo stato CAW per l'archivio dati.
+
Il valore *ATS/CAW* per l'archivio dati dovrebbe visualizzare *Disabled* e la colonna filesystem dovrebbe visualizzare *VMFS.x*.

. Annotare il nome dell'archivio dati nella colonna disco
. Accedere alla console ESXi utilizzando SSH.
. Elencare i dettagli del dispositivo e della partizione:
+
`*~ # vmkfstools -Ph -v1 _datastore_path_*`

+
Percorso_datastore è il nome del datastore dalla colonna Disk di _Inventory Assessment Workbook_.

+
`*# vmkfstools -Ph -v1 /vmfs/volumes/datastorename*`

+
[listing]
----
VMFS-5.60 file system spanning 1 partitions.
File system label (if any): datastorename
Mode: public
Capacity 9.8 GB, 8.2 GB available, file block size 1 MB, max file size 64
TB
Volume Creation Time: Mon Dec 9 10:29:18 2013
Files (max/free): 27408/27394
Ptr Blocks (max/free): 64512/64495
Sub Blocks (max/free): 3968/3964
Secondary Ptr Blocks (max/free): 256/256
File Blocks (overcommit/used/overcommit %): 0/1593/0
Ptr Blocks (overcommit/used/overcommit %): 0/17/0
Sub Blocks (overcommit/used/overcommit %): 0/4/0
Volume Metadata size: 590675968
UUID: 52a59b7e-52d2fb6c-11d6-001ec9d631cb
Partitions spanned (on "lvm"):
naa.600a098044314c6c442b446d51376749:1
naa.600a098054314c6c445d446f79716431:1
naa.600a098054314c6c445d446f79716433:1
Is Native Snapshot Capable: YES
----
. Annotare il nome del primo dispositivo e il numero della partizione.
+
Nell'esempio precedente, `naa.600a098044314c6c442b446d51376749:1` è il nome del dispositivo e il numero della partizione.

. Utilizzare l'ID del dispositivo e il numero della partizione per abilitare CAW nell'archivio dati:
+
`*~# vmkfstools --configATSOnly 1 /vmfs/devices/disks/__device-ID:Partition__*`

. Verificare che il volume VMFS sia stato configurato solo con ATS:
+
`*# vmkfstools -Ph -v1 /vmfs/volumes/VMFS-volume-name*`

+
[listing]
----
VMFS-5.54 file system spanning 1 partitions.
File system label (if any): ats-test-1
Mode: public ATS-only
----


*Informazioni correlate*

xref:task_remounting_vmfs_volumes_after_transition_using_vsphere_client.adoc[Rimontare i volumi VMFS dopo la transizione utilizzando vSphere Client]

xref:task_remounting_vmfs_volumes_after_transition_using_esxi_cli_console.adoc[Rimontare i volumi VMFS dopo la transizione utilizzando la CLI ESXi]

https://pubs.vmware.com/vsphere-55/index.jsp?topic=/com.vmware.vsphere.storage.doc/GUID-6887003D-2322-49AC-A56C-7AFE7350DB5D.html["Documentazione VMware"]
