---
permalink: copy-based/concept_transition_terminology.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, terminology 
summary: La comprensione della terminologia di transizione relativa al 7-Mode Transition Tool ti aiuta a comprendere il processo di transizione. 
---
= Terminologia di transizione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La comprensione della terminologia di transizione relativa al 7-Mode Transition Tool ti aiuta a comprendere il processo di transizione.

* *Raccogliere e valutare*
+
Prima di trasferire dati e configurazioni a ONTAP, è necessario raccogliere informazioni sull'ambiente di storage che include sistemi storage, host e applicazioni. È quindi necessario valutare le caratteristiche e le funzionalità di questi sistemi e identificare il funzionamento di tali funzionalità nella versione ONTAP selezionata per la transizione.

* *Migrate*
+
Si riferisce alla transizione di dati e configurazioni dai volumi 7-Mode a ONTAP. La migrazione deve essere eseguita dopo aver valutato i controller 7-Mode.

* *Progetto*
+
In 7-Mode Transition Tool, un progetto consente di configurare e gestire la transizione di un gruppo di volumi.

+
I progetti di transizione sono di tre tipi: Standalone, primario e secondario.

+
** *Progetto standalone*
+
I volumi di questo progetto non sono in relazione SnapMirror con i volumi di altri sistemi storage o si desidera eseguire la transizione di questi volumi senza mantenere le relazioni di SnapMirror.

** *Progetto primario*
+
I volumi di questo progetto sono i volumi di origine di una relazione SnapMirror.

** *Progetto secondario*
+
I volumi di questo progetto sono i volumi di destinazione di una relazione SnapMirror.



* *Gruppo di progetto*
+
In 7-Mode Transition Tool, un gruppo di progetti è un container logico che è possibile utilizzare per tenere progetti di migrazione correlati. Nel sistema esiste sempre un gruppo predefinito con nome Default_Group.

* *Relazione di transizione tra pari*
+
La relazione di transizione tra pari è un meccanismo di autorizzazione che consente a SnapMirror di stabilire relazioni tra un sistema di storage 7-Mode e una SVM nel cluster per copiare i dati dai volumi 7-Mode ai volumi ONTAP per la transizione. Una relazione peer di transizione può essere creata solo da un amministratore del cluster e viene avviata dal cluster.

* *Relazione di protezione dei dati di transizione*
+
Le relazioni di Transition Data Protection (TDP) sono relazioni SnapMirror di volume stabilite tra un sistema 7-Mode e un sistema ONTAP.

+
La protezione dei dati di transizione è supportata solo per la transizione. Non conservare questa relazione per lunghi periodi di tempo perché non è possibile risincronizzare i dati da un volume ONTAP a un volume 7-Mode.


