---
permalink: copy-based/task_aborting_a_subproject.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, abort, project 
summary: È possibile interrompere un progetto in esecuzione, ad esempio quando le prestazioni del controller o del cluster sono compromesse. È possibile interrompere un progetto in esecuzione dalla dashboard. 
---
= Interruzione di un progetto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile interrompere un progetto in esecuzione, ad esempio quando le prestazioni del controller o del cluster sono compromesse. È possibile interrompere un progetto in esecuzione dalla dashboard.

Prima di interrompere progetti che eseguono la transizione di volumi con relazioni SnapMirror, è necessario considerare quanto segue:

* Se entrambi i progetti sono stati avviati, l'interruzione di un progetto interrompe il progetto associato.
+
Ad esempio, se si interrompe un progetto primario, anche il progetto secondario viene interrotto.

* Se l'operazione di interruzione non riesce sul progetto corrente, il progetto associato non viene interrotto.
* Se viene interrotto solo un progetto attivo, l'operazione di avvio sul progetto associato non riesce.
* Quando si interrompe un progetto primario, l'operazione di copia dal volume primario 7-Mode al volume secondario ONTAP non viene interrotta.
+
Viene interrotta solo l'operazione di copia dal volume primario 7-Mode al volume primario ONTAP corrispondente.




NOTE: Se il progetto 7-Mode viene interrotto, l'unica opzione consiste nell'eliminare il progetto. Non è possibile riprendere o riavviare il progetto dopo l'interruzione.

.Fasi
. Dalla dashboard, selezionare il progetto che si desidera interrompere.
. Fare clic su *Interrompi*.
. Dal cluster, eliminare i volumi ONTAP creati come parte della transizione.
. Dal sistema 7-Mode, rilasciare le relazioni di SnapMirror con i volumi ONTAP.
. Se si interrompe una relazione SnapMirror di un volume, è necessario effettuare le seguenti operazioni:
+
.. Interrompere ed eliminare la relazione di SnapMirror tra i volumi primari 7-Mode e i volumi secondari ONTAP.
.. Dal sistema primario 7-Mode, rilasciare le relazioni di SnapMirror con i volumi secondari di ONTAP.




http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandi di ONTAP 9"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1511537["Data ONTAP 8. 2 comandi: Guida di riferimento pagina manuale per 7-Mode, Volume 1"]
