---
permalink: copy-based/task_starting_data_copy_for_a_transition_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, start, data, copy, project 
summary: È possibile avviare una copia dei dati da volumi 7-Mode a volumi ONTAP per un trasferimento di riferimento. Il trasferimento di riferimento inizia quando le pianificazioni delle copie dei dati configurate in un progetto diventano attive. Una volta completato il trasferimento di riferimento, i volumi ONTAP vengono aggiornati periodicamente in base al programma di copia dei dati. 
---
= Avvio della copia dei dati per un progetto di transizione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile avviare una copia dei dati da volumi 7-Mode a volumi ONTAP per un trasferimento di riferimento. Il trasferimento di riferimento inizia quando le pianificazioni delle copie dei dati configurate in un progetto diventano attive. Una volta completato il trasferimento di riferimento, i volumi ONTAP vengono aggiornati periodicamente in base al programma di copia dei dati.

* È necessario eseguire un controllo preliminare sul progetto e risolvere tutti gli errori.
* Per il trasferimento dei dati, è necessario aver configurato una rete dedicata, a elevata larghezza di banda e a bassa latenza tra i sistemi di origine e di destinazione.
+

NOTE: È possibile utilizzare il multipathing di SnapMirror per bilanciare il carico di trasferimento dei dati tra i due percorsi.

* Per la sessione deve essere configurato un programma di copia dei dati.


Se si sta passando a una SVM esistente, i volumi vengono creati durante questa operazione. Se si sta passando a una nuova SVM, la SVM e i relativi volumi vengono creati durante questa operazione.

Le relazioni di SnapMirror vengono create tra i volumi 7-Mode e ONTAP.

.Fasi
. Avviare la copia dei dati:
+
`*transition start -p _project_name_*`

+
Se l'operazione di avvio non riesce e la copia dei dati non viene avviata, è necessario risolvere i problemi ed eseguire `transition start` di nuovo comando.

+
[listing]
----
7-Mode Transition Tool>transition start -p project_finance

[1/17 ] Project status checks                                      [      Ok       ]
[2/17 ] Validating 7-Mode system information                       [      Ok       ]
[3/17 ] Validating 7-Mode volumes information                      [      Ok       ]
[4/17 ] Validating Cluster-Mode system information                 [      Ok       ]
[5/17 ] Validating Cluster-Mode volume information                 [      Ok       ]
[6/17 ] Validating LIF information                                 [ Notifications ]
[7/17 ] WAFL prechecks                                             [      Ok       ]
[8/17 ] UNIX users and groups prechecks                            [   Warnings    ]
[9/17 ] SnapMirror prechecks                                       [ Notifications ]
[10/17] NFS prechecks                                              [   Warnings    ]
[11/17] Networking prechecks                                       [ Notifications ]
[12/17] CIFS prechecks                                             [   Warnings    ]
[13/17] Name services prechecks                                    [   Warnings    ]
[14/17] SAN prechecks                                              [      Ok       ]
[15/17] Creating Cluster-Mode volumes                              [      Ok       ]
[16/17] Establishing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]
[17/17] Initializing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]

Operation summary:
------------------
The 'start' operation is completed with warnings and notifications.

 0  Errors - No action required
22  Warnings - Need your attention!
16  Notifications - Please review
102  Informational messages

Do you want to see a detailed report {yes, no} [yes]:

22 Warnings:
------------
20362: Checking whether 7-Mode UNIX groups' names are in use in the Vserver 'vs2'.  [    Warning    ]
  > The following 7-Mode UNIX groups' names are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }

20372: Checking whether 7-Mode UNIX groups' ids are in use in the Vserver 'vs2'.    [    Warning    ]
  > The following 7-Mode UNIX groups' ids are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }
----
+
Il progetto passa allo stato copy-baseline. Una volta completato il trasferimento di riferimento, il progetto passa allo stato di copia-aggiornamento.


