---
permalink: copy-based/task_preparing_7_mode_systems_for_inventory_collection.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, prepare, host, assessment 
summary: È necessario assicurarsi che i sistemi 7-Mode e gli host soddisfino determinati requisiti di rete e protocollo per generare correttamente un report di valutazione. 
---
= Preparazione dei sistemi 7-Mode e degli host per la valutazione della transizione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario assicurarsi che i sistemi 7-Mode e gli host soddisfino determinati requisiti di rete e protocollo per generare correttamente un report di valutazione.

.Fasi
. Abilitare HTTPS sul sistema 7-Mode:
+
`*options httpd.admin.ssl.enable on*`

. Abilitare TLS sul sistema 7-Mode:
+
`*options tls.enable on*`

+

IMPORTANT: La procedura consigliata consiste nell'attivare TLS a causa delle vulnerabilità di sicurezza in SSLv3.

. Abilitare SSL e disabilitare SSLv2 e SSLv3 sul sistema 7-Mode:
+
.. Configurazione e avvio di SSL:
+
`*secureadmin setup ssl*`

.. Attiva SSL:
+
`*options ssl.enable on*`

.. Disattivare SSLv2 e SSLv3:
+
`*options ssl.v2.enable off*`

+
`*options ssl.v3.enable off*`

+

IMPORTANT: La procedura consigliata consiste nel disattivare SSLv2 e SSLv3 per evitare vulnerabilità di sicurezza.



. Abilitare SSH sul sistema 7-Mode:
+
.. Configurare SSH sul sistema 7-Mode:
+
`*secureadmin setup -f ssh*`

+
Il `-f` L'opzione forza l'esecuzione dell'installazione anche se il server SSH è già configurato.

.. Abilitare SSH:
+
`*secureadmin enable ssh2*`

.. Abilitare l'autenticazione della password sul server SSH:
+
`*options ssh.passwd_auth.enable*`

.. Abilitare l'accesso SSH all'host: +
`*options ssh.access*`


. Preparazione dei sistemi host Windows:
+
** Abilitare l'accesso WMI.
+
Per ulteriori informazioni sull'abilitazione dell'accesso WMI, consultare la documentazione dell'host.

** Se si dispone di Windows Server 2003, verificare di aver installato il pacchetto Microsoft Fibre Channel Information Tool (fcinfo) ed eseguire lo strumento una volta sul sistema host Windows.
+
Questo strumento consente di raccogliere le informazioni di configurazione HBA dell'host.

** Se il sistema su cui viene eseguito 7-Mode Transition Tool non appartiene a un dominio, verificare quanto segue:
+
*** Il sistema host appartiene a un dominio.
*** Se l'host dispone di un utente locale e il relativo nome utente è nel seguente formato:
+
`SystemName\Username`





. Abilitare SSH sull'host Linux o ESXi.
+
Per ulteriori informazioni sull'abilitazione di SSH, consultare la documentazione dell'host.

. Verificare di aver installato la versione più recente del software NetApp host Utilities per ciascun host.
+
Per informazioni sul download e l'installazione del software NetApp host Utilities, consultare il NetApp Support Site.

. Verificare che tutti gli host e i sistemi storage siano raggiungibili dal sistema Windows da cui viene eseguito 7-Mode Transition Tool.

