---
permalink: copy-based/task_preparing_7_mode_system_for_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, prepare, 7, mode 
summary: 'Prima di avviare una transizione, è necessario completare alcune attività sul sistema 7-Mode, ad esempio l"aggiunta della licenza SnapMirror, l"abilitazione del sistema 7-Mode per comunicare con il cluster di destinazione e l"abilitazione di TLS.' 
---
= Preparazione del sistema 7-Mode per la transizione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di avviare una transizione, è necessario completare alcune attività sul sistema 7-Mode, ad esempio l'aggiunta della licenza SnapMirror, l'abilitazione del sistema 7-Mode per comunicare con il cluster di destinazione e l'abilitazione di TLS.

Tutti i volumi 7-Mode che si desidera trasferire devono essere online.

.Fasi
. Aggiungere e attivare la licenza SnapMirror sul sistema 7-Mode:
+
.. Aggiungere la licenza SnapMirror al sistema 7-Mode:
+
`*license add _license_code_*`

+
`_license_code_` è il codice di licenza acquistato.

.. Attivare la funzionalità SnapMirror: +
`*options snapmirror.enable on*`


. Configurare il sistema 7-Mode e il cluster di destinazione per comunicare tra loro scegliendo una delle seguenti opzioni:
+
** Impostare `snapmirror.access` opzione a tutti.
** Impostare il valore di `snapmirror.access` Agli indirizzi IP di tutte le LIF dell'intercluster sul cluster.
** Se il `snapmirror.access` l'opzione è `legacy` e a. `snapmirror.checkip.enable` l'opzione è `off`, Aggiungere il nome SVM a `/etc/snapmirror.allow` file.
** Se il `snapmirror.access` l'opzione è `legacy` e a. `snapmirror.checkip.enable` l'opzione è `on`, Aggiungere gli indirizzi IP delle LIF di intercluster a `/etc/snapmirror.allow` file.


. Se HTTPS non è abilitato sul sistema di storage, abilitare HTTPS:
+
`*options httpd.admin.ssl.enable on*`

+
HTTPS è attivato per impostazione predefinita.

. Abilitare TLS sui sistemi di storage 7-Mode per consentire al 7-Mode Transition Tool di comunicare con i sistemi 7-Mode:
+
.. Se SSL non è già abilitato sul sistema di storage, configurare e avviare SSL:
+
`*secureadmin setup ssl*`

+
SSL è impostato per impostazione predefinita per i sistemi di storage. Se SSL è stato precedentemente configurato per il sistema di storage, viene richiesto se si desidera continuare. È possibile uscire dalla configurazione SSL se non si desidera apportare modifiche.

.. Attiva SSL:
+
`*options ssl.enable on*`

+
Questa opzione deve essere attivata per consentire la comunicazione su TLS.

.. Abilita TLS:
+
`*options tls.enable on*`

.. Disattivare SSLv2 e SSLv3 sul sistema 7-Mode:
+
`*options ssl.v2.enable off*`

+
`*options ssl.v3.enable off*`



+
7-Mode Transition Tool utilizza i protocolli TLS o SSL per comunicare con i sistemi storage 7-Mode. Lo strumento comunica con il sistema di storage utilizzando il protocollo TLS se TLS è attivato sul sistema di storage. Se TLS è disattivato e SSLv3 è attivato su un sistema di storage, lo strumento utilizza SSLv3 per comunicare con il sistema di storage.

+
+ IMPORTANTE: La procedura consigliata consiste nell'attivare TLS e disattivare SSLv2 e SSLv3 per evitare vulnerabilità della sicurezza.

. A seconda della versione Data ONTAP del sistema 7-Mode, attenersi alla seguente procedura:
+
.. Consentire il traffico SnapMirror su tutte le interfacce:
+
`*options interface.blocked.snapmirror ""*`

.. Se si utilizza Data ONTAP versione 7.3.7, 8.0.3 o 8.1 e si utilizza l'indirizzo IP dell'interfaccia e0M come indirizzo IP di gestione per interagire con 7-Mode Transition Tool, consentire il traffico dati sull'interfaccia e0M:
+
`*options interface.blocked.mgmt_data_traffic off*`



. Se sono state impostate le opzioni I2P, Read Allocations o NVFAIL sul volume, attenersi alla seguente procedura:
+
.. Verificare che le altre operazioni non siano interessate se queste opzioni sono disattivate.
.. Disattivare le opzioni:
+
`*vol options vol_name no_i2p off*`

+
`*vol options vol_name read_realloc off*`

+
`*vol options vol_name nvfail off*`




