---
settings:
  name: ONTAP 7-Mode Transition
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Transizione 7-Mode
    url: "/index.html"
  - title: Note di rilascio
    url: "/releasenotes.html"
  - section: command-map
  - section: install-admin
  - section: copy-based
  - section: copy-free
  - section: inventory-collect
  - section: snapmirror
  - section: san-host
  - title: Note legali
    url: "/reference_legal_notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
