---
settings:
  name: ONTAP 7-Mode Transition
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Transizione 7-Mode
    url: "/index.html"
  - title: Note di rilascio
    url: "/releasenotes.html"
  - section: command-map
  - section: install-admin
  - section: copy-based
  - section: copy-free
  - section: inventory-collect
  - section: snapmirror
  - section: san-host
  - title: Note legali
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Novità
      summary: Scopri le novità dell'ultima versione di 7-Mode Transition Tool
      url: releasenotes.html
    - title: Installare 7-Mode Transition Tool
      summary: Scopri come installare il tool su Microsoft Windows o Linux
      url: "/install-admin/concept_transition_to_clustered_ontap_using_7mtt.html"
    - title: Raccogliere i dati necessari per la transizione
      summary: Scopri come raccogliere informazioni essenziali per la transizione
      url: "/inventory-collect/concept_collecting_host_and_storage_inventory_information_for_transition_assessment.html"
  - title: Mappa dei comandi per amministratori in 7 modalità
    links:
    - title: Come i comandi 7-Mode si associano ai comandi ONTAP
      summary: Trova gli equivalenti ONTAP dei comandi 7-Mode
      url: "/command-map/reference_how_7_mode_commands_map_to_clustered_ontap_commands.html"
    - title: Come le opzioni 7-Mode si associano ai comandi ONTAP
      summary: Scopri come le opzioni 7-Mode si associano ai parametri dei comandi
        ONTAP
      url: "/command-map/reference_how_7_mode_options_map_to_clustered_ontap_commands.html"
    - title: Come i file di configurazione 7-Mode si associano ai comandi ONTAP
      summary: Scopri come i file di configurazione 7-Mode si associano ai comandi
        di configurazione di ONTAP
      url: "/command-map/reference_how_7_mode_configuration_files_map_to_clustered_ontap_commands.html"
  - title: Modi per passare
    links:
    - title: Transizione basata sulla copia
      summary: Utilizza lo strumento per eseguire una transizione basata su copia
        da 7-Mode a ONTAP
      url: "/copy-based/concept_copy_based_transition_workflow.html"
    - title: Transizione senza copia
      summary: Utilizza lo strumento per eseguire una transizione senza copia da 7-Mode
        a ONTAP
      url: "/copy-free/task_copy_free_transition_workflow.html"
    - title: Transizione dei dati con SnapMirror
      summary: Scopri come trasferire i dati da 7-Mode a ONTAP utilizzando i comandi
        SnapMirror
      url: "/snapmirror/task_transitioning_7_mode_volumes_using_snapmirror.html"
  - title: Transizione e correzione degli host SAN
    links:
    - title: VMware ESXi
      summary: Comprendere i requisiti pre e post-transizione per gli host VMware
        ESXi
      url: "/san-host/concept_vmware_esxi_host_remediation.html"
    - title: Red Hat Enterprise Linux
      summary: Comprendere i requisiti pre e post-transizione per gli host Red Hat
        Enterprise Linux
      url: "/san-host/concept_linux_host_remediation.html"
    - title: Windows
      summary: Comprendere i passaggi pre e post-transizione per gli host Microsoft
        Windows
      url: "/san-host/concept_windows_host_remediation.html"
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: Tutta la documentazione del prodotto ONTAP
