---
permalink: command-map/concept_how_to_interpret_clustered_ontap_command_maps_for_7_mode_administrators.html 
sidebar: sidebar 
keywords: ontap, command, map, transition, clustered, commands, options, configuration, file, maps, interpret 
summary: Se si sta passando da Data ONTAP in esecuzione in 7-Mode a Clustered Data ONTAP, potrebbe essere utile fare riferimento alle mappe dei comandi, che mostrano gli equivalenti di Clustered Data ONTAP dei comandi, delle opzioni e dei file di configurazione 7-Mode. 
---
= Come interpretare i comandi, le opzioni e le mappe dei file di configurazione di Clustered Data ONTAP per gli amministratori 7-Mode
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si sta passando da Data ONTAP in esecuzione in 7-Mode a Clustered Data ONTAP, potrebbe essere utile fare riferimento alle mappe dei comandi, che mostrano gli equivalenti di Clustered Data ONTAP dei comandi, delle opzioni e dei file di configurazione 7-Mode.



== Quali informazioni di mappatura sono incluse

La mappa dei comandi per gli amministratori 7-Mode include i seguenti mapping di comandi 7-Mode, opzioni e file di configurazione ai relativi equivalenti Data ONTAP in cluster:

* xref:reference_how_7_mode_commands_map_to_clustered_ontap_commands.adoc[Come i comandi 7-Mode si associano ai comandi Data ONTAP in cluster]
* xref:reference_how_7_mode_options_map_to_clustered_ontap_commands.adoc[Come le opzioni 7-Mode si associano ai comandi Data ONTAP in cluster]
* xref:reference_how_7_mode_configuration_files_map_to_clustered_ontap_commands.adoc[Come i file di configurazione 7-Mode si associano ai comandi Data ONTAP in cluster]




== Come interpretare i comandi di scelta rapida compatibili con 7-Mode

Sebbene l'interfaccia della riga di comando (CLI) di Data ONTAP sia notevolmente riorganizzata per le operazioni del cluster, molti dei comandi dispongono di versioni di collegamento compatibili con 7-Mode che non richiedono modifiche agli script o ad altre attività automatizzate. Queste versioni dei collegamenti sono elencate per prime e in *grassetto* nelle tabelle qui riportate. Di seguito sono elencate le versioni dei collegamenti non compatibili con 7-Mode, seguite dalla versione completa dei comandi:

|===
| Comando 7-Mode | Comando Clustered Data ONTAP 


 a| 
`aggr add`
 a| 
`*aggr add*`

`aggr add-disks`

`storage aggregate add-disks`

|===
Se non è elencato alcun collegamento *bold*, non è disponibile una versione compatibile con 7-Mode. Non tutte le forme dei comandi sono mostrate nella tabella. L'interfaccia CLI è estremamente flessibile e consente di utilizzare più moduli abbreviati.



== Comprensione delle diverse shell Data ONTAP in cluster per i comandi CLI

Un cluster dispone di tre diverse shell per i comandi CLI:

* La _clustershell_ è la shell nativa, avviata automaticamente quando si accede al cluster.
+
Fornisce tutti i comandi necessari per configurare e gestire il cluster.

* La _nodeshell_ è una shell speciale che consente di eseguire un sottoinsieme di comandi 7-Mode.
+
Questi comandi hanno effetto solo a livello di nodo. Puoi passare dalla clustershell a una sessione nodeshell per eseguire i comandi nodeshell in modo interattivo, oppure puoi eseguire un singolo comando nodeshell dalla clustershell. Puoi riconoscere un comando come comando nodeshell se ha la forma (lunga) `system node run -node {_nodename_|local} commandname`.

* La _systemshell_ è una shell di basso livello utilizzata solo per scopi di diagnostica e troubleshooting.
+
Non è destinato a scopi amministrativi generali. Accedere alla shell del sistema solo con la guida del supporto tecnico.





== Passare al nodeshell

Quando vedi una versione di scorciatoia compatibile con 7-Mode di un comando nodeshell, si presume che stai eseguendo il comando dal nodeshell. Per passare al nodeshell, immettere quanto segue:

`*system node run -node {_nodename_|local}*`

Altre forme di `nodeshell` il comando deve essere eseguito dalla shell del clustershell.



== Dove andare per ulteriori informazioni

|===
| Se si desidera... | Per ulteriori informazioni... 


 a| 
Utilizzare i comandi della shell clustershell
 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandi di ONTAP 9"]



 a| 
USA i comandi nodeshell
 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMP1511537["Data ONTAP 8. 2 comandi: Guida di riferimento pagina manuale per 7-Mode, Volume 1"]



 a| 
Eseguire i comandi CLI, esplorare le directory dei comandi CLI, impostare i valori nella CLI e utilizzare query, modelli e caratteri jolly
 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html["Amministrazione del sistema"]

|===