---
permalink: copy-free/concept_requirements_for_copy_free_transition.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, requirements 
summary: Devi essere consapevole dei requisiti per i sistemi 7-Mode, i cluster, le release ONTAP e gli shelf di dischi per la transizione senza copia. 
---
= Requisiti per la transizione senza copia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Devi essere consapevole dei requisiti per i sistemi 7-Mode, i cluster, le release ONTAP e gli shelf di dischi per la transizione senza copia.

Consulta l'attuale 7-Mode Transition Tool _Release Notes_ per le informazioni più recenti sulle release di destinazione supportate e sui problemi noti.

link:https://docs.netapp.com/us-en/ontap-7mode-transition/releasenotes.html["7-Mode Transition Tool Release Notes"]

* *Modelli di piattaforma*
+
La transizione senza copia è supportata solo sui sistemi FAS di fascia media e alta e sui sistemi IBM serie N. Il https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"] Contiene le informazioni più recenti sulle piattaforme supportate per i sistemi 7-Mode e i nodi del cluster di destinazione.

* *Data ONTAP nei sistemi di origine 7-Mode*
+
Per un elenco delle release 7-Mode supportate per la migrazione da 7-Mode Transition Tool, vedere https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"]

* *Sistemi di destinazione ONTAP*
+
7-Mode Transition Tool versione 3.3.1 supporta la transizione alle seguenti release di ONTAP utilizzando il metodo copy-free:

+
** ONTAP 9.4 e versioni precedenti di ONTAP 9
** Clustered Data ONTAP 8.3.2 e versioni successive 8.x *Nota:* non è possibile utilizzare lo strumento di transizione 7-Mode per passare a ONTAP 9.5 o versioni successive utilizzando il metodo senza copia. A tale scopo, è necessario prima passare a ONTAP 9.4 utilizzando lo strumento di transizione 7-Mode 3.3.1 e quindi aggiornare il cluster a ONTAP 9.5 o versione successiva. 7-Mode Transition Tool 3.3.2 non supporta transizioni senza copia.


* *Configurazione ha*
+
I controller 7-Mode e i nodi del cluster di destinazione devono essere in una configurazione ha. Le coppie ha devono essere integre e nessuno dei nodi può essere in modalità Takeover. I controller standalone non sono supportati per la transizione senza copia.

* *Modelli di shelf di dischi*
+
Sono supportati i seguenti modelli di shelf di dischi:

+
** DS4486
** DS4246
** DS4243
+

NOTE: Il modello di shelf di dischi DS4243 non è supportato con ONTAP 9.2 e ONTAP 9.4. Questo modello è supportato con tutte le release di patch di ONTAP 9.2 a partire da ONTAP 9.2P1 e con ONTAP 9.3. 7-Mode Transition Tool 3.3.1 supporta la transizione con il modello di shelf di dischi DS4243 per la transizione senza copia a ONTAP 9.2P1 fino a ONTAP 9.3.

** DS2246
** DS14mk4 FC (non supportato in ONTAP 9.0 e versioni successive)
** DS14mk2 AT (non supportato in ONTAP 9.0 e versioni successive)





NOTE: Il modello di shelf di dischi DS14mk2 FC non è supportato.

* *Firmware del disco*
+
È necessario scaricare e installare il pacchetto di qualificazione dei dischi più recente, il firmware dei dischi, lo shelf di dischi e il firmware ACP sui sistemi 7-Mode e sui nodi del cluster di destinazione.

+
https://mysupport.netapp.com/NOW/download/tools/diskqual/["Download NetApp: Pacchetto di qualificazione dei dischi"]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Download NetApp: Firmware del disco"]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Download NetApp: Firmware shelf di dischi"]

* *Tool per verificare il cablaggio*
+
Dopo aver collegato gli shelf di dischi 7-Mode ai nodi del cluster di destinazione durante la transizione, è necessario utilizzare Config Advisor per verificare il cablaggio.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Download NetApp: Config Advisor"]


