---
permalink: copy-free/concept_restrictions_for_copy_free_transition.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, aggregates, volumes, restrictions 
summary: 'È necessario conoscere alcune limitazioni per la transizione di aggregati e volumi 7-Mode. Alcune limitazioni sono dovute a funzionalità non supportate in ONTAP. Per alcune limitazioni, è possibile eseguire un"azione correttiva che consente di continuare con la transizione.' 
---
= Restrizioni per la transizione di volumi e aggregati 7-Mode
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario conoscere alcune limitazioni per la transizione di aggregati e volumi 7-Mode. Alcune limitazioni sono dovute a funzionalità non supportate in ONTAP. Per alcune limitazioni, è possibile eseguire un'azione correttiva che consente di continuare con la transizione.



== Tipi di volume

I seguenti tipi di volumi non sono supportati per la transizione:

* Volumi tradizionali
+
È possibile utilizzare metodi di transizione basati su host per la transizione dei volumi tradizionali.

+
https://www.netapp.com/pdf.html?item=/media/19510-tr-4052.pdf["Report tecnico di NetApp 4052: Passaggio riuscito a Clustered Data ONTAP (Data ONTAP 8.2.x e 8.3)"^]

* Volumi SnapLock
+
La transizione di SnapLock Volumes è supportata per tutte le ultime release di ONTAP.

* Volumi FlexCache




== Stati di aggregati e volumi

La transizione viene bloccata se uno qualsiasi degli aggregati 7-Mode e dei volumi selezionati per la transizione si trova in uno dei seguenti stati:

* Offline
* Limitato
* Incoerente (`wafl inconsistent`)




== Volumi FlexClone

La gerarchia dei cloni e l'efficienza dello storage vengono preservate durante la transizione senza copia. Tuttavia, è necessario assicurarsi che il volume FlexVol padre e tutti i volumi FlexClone appartengano alla stessa unità vFiler. Se i volumi FlexClone si trovano in unità vFiler diverse dal volume padre, è necessario scegliere una delle seguenti azioni:

* Spostare i volumi FlexClone nell'unità vFiler che possiede il volume FlexVol padre.
* Suddividere i cloni dal volume FlexClone padre, quindi trasferire questi volumi come volumi FlexVol.




== Volume con qtree che appartengono a un'unità vFiler diversa

Non è possibile eseguire la transizione di volumi con qtree, in cui i qtree sono di proprietà di un'unità vFiler diversa da quella del volume. Prima della transizione, è necessario assicurarsi che ciascun volume e tutti i relativi qtree appartengano alla stessa unità vFiler eseguendo una delle seguenti operazioni:

* Spostare i qtree nell'unità vFiler proprietaria del volume.
* Eliminare i qtree.




== Impostazione di conversione inode to pathname padre

Le traduzioni inode to pathname padre devono essere attivate su ciascun volume. È possibile abilitare la traduzione del nome del percorso per l'origine disattivando l'opzione no_i2p:

`*vol options _vol_name_ no_i2p off*`

Non è necessario attendere il completamento della scansione i2p ed è possibile continuare con la preparazione della transizione.
