---
permalink: copy-free/task_preparing_cluster_for_transitioning_volume_snapmirror_relationships.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, prepare, cluster, snapmirror, relationship 
summary: Per la transizione delle relazioni SnapMirror del volume 7-Mode, è necessario aggiungere la licenza SnapMirror ai cluster di origine e di destinazione. È inoltre necessario creare una relazione peer del cluster tra i cluster in cui vengono trasferiti i volumi primari e secondari delle relazioni SnapMirror e creare le pianificazioni SnapMirror. 
---
= Preparazione del cluster per la transizione delle relazioni SnapMirror del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per la transizione delle relazioni SnapMirror del volume 7-Mode, è necessario aggiungere la licenza SnapMirror ai cluster di origine e di destinazione. È inoltre necessario creare una relazione peer del cluster tra i cluster in cui vengono trasferiti i volumi primari e secondari delle relazioni SnapMirror e creare le pianificazioni SnapMirror.

È necessario aver registrato le pianificazioni di SnapMirror definite in `/etc/snapmirror.conf` File del sistema secondario 7-Mode.

.Fasi
. Aggiungere la licenza SnapMirror ai cluster di origine e di destinazione:
+
`*system license add _license_code_*`

. Da ciascun cluster, creare la relazione peer del cluster.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html["Configurazione rapida del peering di cluster e SVM"]

. Creare pianificazioni sulle SVM secondarie corrispondenti alle pianificazioni nel sistema secondario 7-Mode:
+
`*job schedule cron create*`



*Informazioni correlate*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandi di ONTAP 9"]
