---
permalink: copy-free/task_selecting_target_cluster_for_transition.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, select, target, cluster, nodes 
summary: È possibile selezionare la coppia ha del cluster di destinazione e mappare ciascun controller 7-Mode della coppia ha a un nodo del cluster di destinazione corrispondente. Il nodo mappato specifica il nodo del cluster a cui devono essere collegati gli shelf di dischi del controller 7-Mode corrispondente. 
---
= Selezione dei nodi del cluster di destinazione per la transizione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile selezionare la coppia ha del cluster di destinazione e mappare ciascun controller 7-Mode della coppia ha a un nodo del cluster di destinazione corrispondente. Il nodo mappato specifica il nodo del cluster a cui devono essere collegati gli shelf di dischi del controller 7-Mode corrispondente.

Il cluster di destinazione deve eseguire Data ONTAP 8.3.2 o versione successiva.

È possibile trasferire gli shelf di dischi 7-Mode a una coppia ha di destinazione con volumi e aggregati di dati preesistenti.

Per un cluster a due nodi, è necessario disporre di un aggregato di dati per ospitare i volumi root delle SVM di destinazione. Per un cluster con quattro o più nodi, i volumi root delle SVM possono essere ospitati sui nodi di destinazione della transizione o su altri nodi del cluster.

.Fasi
. Selezionare la coppia ha di destinazione a cui devono essere collegati gli shelf di dischi 7-Mode.
+
Lo strumento esegue automaticamente il mapping di ciascun sistema di storage 7-Mode a un nodo del cluster di destinazione.

+

NOTE: La proprietà del disco e dell'aggregato da ciascun controller 7-Mode viene trasferita al nodo del cluster di destinazione mappato corrispondente durante la fase di importazione.

. Fare clic su *Swap Node Mapping* (mappatura nodo di scambio) per modificare l'assegnazione automatica della mappatura del nodo da origine a destinazione.
. Fare clic su *Salva e continua*.
+
Viene visualizzata la schermata SVM and Volume Mapping (SVM e mappatura volume).


