---
permalink: copy-free/task_transitioning_primary_and_secondary_systems_of_a_snapmirror_relationship_in_parallel.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, primary, secondary, system, snapmirror, relationship, parallel 
summary: È possibile trasferire in parallelo le coppie ha primaria e secondaria che contengono i volumi di una relazione SnapMirror 7-Mode. È quindi necessario impostare manualmente la relazione SnapMirror del volume in Clustered Data ONTAP dopo la transizione. La relazione di SnapMirror viene mantenuta dopo la transizione senza richiedere una nuova baseline. 
---
= Transizione dei sistemi primari e secondari in una relazione SnapMirror in parallelo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile trasferire in parallelo le coppie ha primaria e secondaria che contengono i volumi di una relazione SnapMirror 7-Mode. È quindi necessario impostare manualmente la relazione SnapMirror del volume in Clustered Data ONTAP dopo la transizione. La relazione di SnapMirror viene mantenuta dopo la transizione senza richiedere una nuova baseline.

È necessario aver preparato i cluster di origine e di destinazione per la transizione delle relazioni SnapMirror.

xref:task_preparing_cluster_for_transitioning_volume_snapmirror_relationships.adoc[Preparazione del cluster per la transizione delle relazioni SnapMirror del volume]

È necessario eseguire la transizione delle coppie ha secondaria e primaria nella stessa finestra di cutover.

.Fasi
. Dallo strumento di transizione 7-Mode, eseguire una transizione senza copia delle due coppie ha che contengono i volumi primari e secondari della relazione SnapMirror del volume 7-Mode.
+
Prima di eseguire la transizione della coppia ha 7-Mode che contiene i volumi secondari, non è necessario alcun intervento manuale per le relazioni SnapMirror 7-Mode. In questo modo, i volumi secondari 7-Mode vengono trasferiti come volumi di sola lettura a ONTAP.

+
xref:task_performing_copy_free_transition_of_7_mode_aggregates.adoc[Transizione di aggregati 7-Mode con transizione senza copia]

. Creare una relazione peer SVM tra cluster tra le SVM che contengono i volumi primari e secondari in transizione.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html["Amministrazione del sistema"]

. Creare una relazione SnapMirror di un volume tra i volumi primari e secondari in transizione.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-cg/home.html["Preparazione rapida del disaster recovery dei volumi"]

. Sul volume di destinazione, risincronizzare il volume di origine e il volume di destinazione della relazione SnapMirror:
+
`*snapmirror resync*`

+

IMPORTANT: Tra i volumi di origine e di destinazione deve esistere almeno una copia Snapshot comune.

+
*Risoluzione dei problemi:* la risincronizzazione di SnapMirror non riesce se la copia Snapshot comune è stata creata in una release di Data ONTAP precedente alla 8.1. È possibile utilizzare `-fs-version` con il `volume snapshot show` Nel livello di privilegio avanzato per visualizzare la release in cui è stata creata la copia Snapshot. Se si verifica questo problema, interrompere la relazione SnapMirror ed eseguire la risincronizzazione.

. Monitorare lo stato dei trasferimenti di dati di SnapMirror:
+
`*snapmirror show*`

+

IMPORTANT: Non eseguire alcuna operazione, ad esempio spostamento del volume o interruzione di SnapMirror, sui volumi di origine e di destinazione fino a quando la risincronizzazione non viene completata correttamente. Assicurarsi che la risincronizzazione non venga interrotta e completata correttamente; in caso contrario, i volumi potrebbero andare in uno stato incoerente.

. Eseguire la transizione del progetto secondario, seguita dal progetto primario.
+
xref:task_committing_7_mode_aggregates_to_clustered_ontap_format.adoc[Impegno del progetto di transizione senza copia]



*Informazioni correlate*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Comandi di ONTAP 9"]

https://docs.netapp.com/us-en/ontap/["System Manager"]
