---
permalink: copy-free/task_configuring_zones_by_using_fc_zone_plan.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, zones, fc, plans 
summary: Prima di eseguire la transizione di un ambiente SAN FC, è necessario configurare le zone utilizzando il pianificatore di zona FC per raggruppare gli host e le destinazioni iniziatori. 
---
= Configurazione delle zone mediante il piano di zona FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire la transizione di un ambiente SAN FC, è necessario configurare le zone utilizzando il pianificatore di zona FC per raggruppare gli host e le destinazioni iniziatori.

* Il pianificatore di zona FC deve essere generato utilizzando la funzione Collect and Access di 7-Mode Transition Tool
* Il file script della zona FC deve essere accessibile.
+
.. In caso di modifiche alle configurazioni di igroup sui sistemi 7-Mode, modificare e rigenerare il piano di zona FC.
+
xref:task_generating_an_assessment_report_by_adding_systems_to_7mtt.adoc[Generazione di un report di valutazione mediante l'aggiunta di sistemi al 7-Mode Transition Tool]

.. Accedere alla CLI dello switch.
.. Copiare ed eseguire i comandi di zona richiesti uno alla volta.
+
Nell'esempio seguente vengono eseguiti i comandi di zona sullo switch:

+
[listing]
----
switch1:admin>config terminal
# Enable NPIV feature
feature npiv
zone name auto_transition_igroup_d31_194bf3 vsan 10
member pwwn 21:00:00:c0:dd:19:4b:f3
member pwwn 20:07:00:a0:98:32:99:07
member pwwn 20:09:00:a0:98:32:99:07
.......
.......
.......
copy running-config startup-config
----
.. Verificare l'accesso ai dati dal cluster utilizzando gli host iniziatori di test.
.. Al termine della verifica, attenersi alla seguente procedura:
+
... Scollegare gli host iniziatori del test.
... Rimuovere la configurazione della zona.





